#!/bin/sh

if [ -n "${USERNAME}" -a -n "${PASSWORD}" ]; then
    supertuxkart --init-user --login=${USERNAME} --password=${PASSWORD}
fi

exec supertuxkart --server-config=config.xml --no-graphics --lan-server="${SERVER_NAME:-'STK Server'}"
